//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Champion
    {
        public int ChampionID { get; set; }
        public string ChampionName { get; set; }
        public string RoleName { get; set; }
        public string PrimaryAttribute { get; set; }
    }
}
