//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string TeamName { get; set; }
        public string LeagueName { get; set; }
        public string RoleName { get; set; }
    }
}
